### ISSUE TITLE
Additional Tyra Scene Arts from "Tyra's Bizarre Adventure"

### ISSUE THREAD

**Issue by Phantasm000** [MizaGBF/GBFAL#1]
Would you be able to add the new Tyra Scene Art expressions to her current page? https://mizagbf.github.io/GBFAL/?id=3992885000

The current page only has art from Auld Lang Syne 2022 and she has new expressions added with the new event for example: https://prd-game-a1-granbluefantasy.akamaized.net/assets_en/img/sp/quest/scene/character/body/3992885000_cry.png https://prd-game-a1-granbluefantasy.akamaized.net/assets_en/img/sp/quest/scene/character/body/3992885000_cry2.png https://prd-game-a1-granbluefantasy.akamaized.net/assets_en/img/sp/quest/scene/character/body/3992885000_weak.png https://prd-game-a1-granbluefantasy.akamaized.net/assets_en/img/sp/quest/scene/character/body/3992885000_suddenly2.png with probably more as well

Thank you

**Comment by MizaGBF** [comment]
I'll add them.
It might take a few days to go over all the npcs and characters.
Thanks for pointing it out.

EDIT: I pushed an update for her earlier, to test it out.
The remaining npcs will be here in 6 hours or so.

EDIT²: Process is complete for all npcs, characters and skins.
